# Copyright (C) 2022 ImmortalWrt.org

include $(TOPDIR)/rules.mk

PKG_VERSION:=21202401
PKG_RELEASE:=1

LUCI_TITLE:=LuCI support for Multi stream daemon lite
LUCI_DEPENDS:=+msd_lite
LUCI_PKGARCH:=all

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
